# version: "3"

services:
  db:
    image: postgres:alpine
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=dockeruser
    - POSTGRES_PASSWORD=abc123!
    - POSTGRES_DB=pets
    volumes:
    - pg-data:/var/lib/postgresql/data
    - ./db:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    ports:
    - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: abc123@abc123.co.kr
      PGADMIN_DEFAULT_PASSWORD: abc123!
    volumes:
    - pgadmin-data:/var/lib/pgadmin

  web:
    image: zzyzzy/webapp
    build: web
    ports:
    - 3000:3000
    environment:
    - DB_HOST=db
    depends_on:
    - db

volumes:
  pg-data:
  pgadmin-data:




